---
- name: build network automation inventory report
  hosts: routers
  gather_facts: False

  vars:
    desired_version: "7.0(3)I7(1)"
    # file_path: /var/www/html/generated_report.html
    file_path: "{{playbook_dir}}"
  tasks:
    - name: RETRIEVE FACTS
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: get_facts.yml
      when: ansible_network_os is defined

    - name: create HTML report
      template:
        src: report.j2
        dest: "{{ file_path }}"
      delegate_to: localhost
      run_once: true
